RecommendMusicToMe/Controllers/SpotifyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.IO;
using System.Diagnostics;
using System.Runtime.Caching;
using RecommendMusicToMe.Models;

namespace RecommendMusicToMe.Controllers
{
    public class SpotifyController : Controller
    {
        static SpotifyServices spotService = new SpotifyServices();


        private ObjectCache cache = MemoryCache.Default;

        private SearchCriteriaModel GetCriteriaClass()
        {
            SearchCriteriaModel criteriaSpotify;
            if (cache["SearchCriteriaModel"] == null)
            {
                criteriaSpotify = new SearchCriteriaModel();
                cache["SearchCriteriaModel"] = criteriaSpotify;
            }
            else
            {
                criteriaSpotify = (SearchCriteriaModel)cache["SearchCriteriaModel"];
            }
            return criteriaSpotify;
        }

        // GET: Spotify
        public ActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddFavouriteTrack(SearchCriteriaModel criteriaSpotify, string addtrackid, string addtrackname)
        {
            if (addtrackid != null && addtrackname != null)
                if (addtrackid != "" && addtrackname != "")
                {
                    if (!criteriaSpotify.FavouriteTracks.Exists(x => x.TrackID == addtrackid))
                    {
                        var newTrack = new FavouriteTrackItem();
                        newTrack.TrackID = addtrackid;
                        newTrack.TrackName = addtrackname;
                        criteriaSpotify.FavouriteTracks.Add(newTrack);
                    }
                }
            cache["SearchCriteriaModel"] = criteriaSpotify; // store in cache

            return RedirectToAction("ListSearchResults", new { searchText = criteriaSpotify.SearchText });
        }


        public ActionResult ListSearchResults(string searchText)
        {
            var criteriaSpotify = GetCriteriaClass();
            if (searchText != "")
                criteriaSpotify.SearchText = searchText;
            return ListSearchResults(criteriaSpotify);
        }

        public ActionResult ListSearchResultsNextPage()
        {
            var criteriaSpotify = GetCriteriaClass();
            criteriaSpotify.PageNumber++;
            cache["SearchCriteriaModel"] = criteriaSpotify; // store in cache
            return ListSearchResults(criteriaSpotify);
        }


        [HttpPost]
        public ActionResult ListSearchResults(SearchCriteriaModel criteriaSpotify)
        {
            if (criteriaSpotify == null)
            {
                criteriaSpotify = GetCriteriaClass();
            }
            spotService.AccessToken = (string)cache["access_token"];
            //

            if (ModelState.IsValid)
            {
                // save?
                //return RedirectToAction("Index");
                var searchResults = spotService.GetSearchResults(criteriaSpotify.SearchText, criteriaSpotify.TypeParamString(), criteriaSpotify.PageSize, (criteriaSpotify.PageNumber - 1) * criteriaSpotify.PageSize);


                criteriaSpotify.IsNextPage = false;
                if (searchResults != null)
                {
                    if (searchResults.albums == null ? false : searchResults.albums.items.Count == criteriaSpotify.PageSize)
                        criteriaSpotify.IsNextPage = true;
                    if (searchResults.artists == null ? false : searchResults.artists.items.Count == criteriaSpotify.PageSize)
                        criteriaSpotify.IsNextPage = true;
                    if (searchResults.playlists == null ? false : searchResults.playlists.items.Count == criteriaSpotify.PageSize)
                        criteriaSpotify.IsNextPage = true;
                    if (searchResults.tracks == null ? false : searchResults.tracks.items.Count == criteriaSpotify.PageSize)
                        criteriaSpotify.IsNextPage = true;
                }

                ViewBag.SearchSpotify = searchResults;
            }

            return View(criteriaSpotify);
        }


        public ActionResult ListSearchResults_Spent(string searchNow, bool? ShowAlbum, bool? ShowPlaylist, bool? ShowArtist, bool? ShowTrack, int? ShowPage)
        {
            spotService.AccessToken = (string)cache["access_token"];
            var criteriaSpotify = GetCriteriaClass();

            criteriaSpotify.SearchText = searchNow;
            if (ShowAlbum.HasValue)
                criteriaSpotify.ListAlbums = ShowAlbum.Value;
            if (ShowPlaylist.HasValue)
                criteriaSpotify.ListPlaylist = ShowPlaylist.Value;
            if (ShowArtist.HasValue)
                criteriaSpotify.ListArtists = ShowArtist.Value;
            if (ShowTrack.HasValue)
                criteriaSpotify.ListTrack = ShowTrack.Value;

            if (ShowPage.HasValue)
                criteriaSpotify.PageNumber = ShowPage.Value;

            var searchResults = spotService.GetSearchResults(searchNow, criteriaSpotify.TypeParamString(), criteriaSpotify.PageSize, (criteriaSpotify.PageNumber - 1) * criteriaSpotify.PageSize);


            criteriaSpotify.IsNextPage = false;
            if (searchResults != null)
            {
                if (searchResults.albums == null ? false : searchResults.albums.items.Count == criteriaSpotify.PageSize)
                    criteriaSpotify.IsNextPage = true;
                if (searchResults.artists == null ? false : searchResults.artists.items.Count == criteriaSpotify.PageSize)
                    criteriaSpotify.IsNextPage = true;
                if (searchResults.playlists == null ? false : searchResults.playlists.items.Count == criteriaSpotify.PageSize)
                    criteriaSpotify.IsNextPage = true;
                if (searchResults.tracks == null ? false : searchResults.tracks.items.Count == criteriaSpotify.PageSize)
                    criteriaSpotify.IsNextPage = true;
            }

            ViewBag.SearchSpotify = searchResults;
            return View(criteriaSpotify);
        }


        public ActionResult FirstSearchResults()
        {
            string searchText = "blues";

            spotService.AccessToken = (string)cache["access_token"];

            // LOAD Recommendation stuff
            spotService.LoadSeedGenres();

            ViewBag.SearchQuery = searchText;
            ViewBag.SearchSpotify = spotService.GetSearchResults(searchText, "album,artist,playlist,track", 40, 0);

            return View();
        }

        public ActionResult callback(string access_token, string token_type, string expires_in, string state)
        {
            if (string.IsNullOrEmpty(access_token))
                return View();

            cache["access_token"] = access_token;
            cache["token_type"] = token_type;
            cache["expires_in"] = expires_in;
            cache["state"] = state;

            spotService.AccessToken = access_token;

            SpotifyUserInfo spotUser = spotService.GetUserProfile();

            SpotifyPlaylists spotPlays = spotService.GetPlaylists(spotUser.UserID);

            ViewBag.Playlists = spotPlays;

            return View();
        }

        [HttpPost]
        public ActionResult Recommendations(SearchCriteriaModel criteriaSpotify)
        {
            spotService.AccessToken = (string)cache["access_token"];

            var newRecSearch = new SpotifyRecSearch();

            newRecSearch.seed_tracks = string.Join(",", criteriaSpotify.FavouriteTracks.Select(x => x.TrackID).ToList());
            newRecSearch.seed_artists = "";
            newRecSearch.seed_genres = criteriaSpotify.seed_genres;
            newRecSearch.market = "SE";
            newRecSearch.limit = 50;

            newRecSearch.target_popularity = criteriaSpotify.target_popularity;
            newRecSearch.target_danceability = criteriaSpotify.target_danceability;
            newRecSearch.target_energy = criteriaSpotify.target_energy;
            newRecSearch.target_tempo = criteriaSpotify.target_tempo;
            newRecSearch.target_valence = criteriaSpotify.target_valence;

            var recResults = spotService.GetRecommendations(newRecSearch);

            ViewBag.Recommendations = recResults;
            ViewBag.GenreList = spotService.genres;

            return View(criteriaSpotify);
        }

        public ActionResult GetRecommendations(string someQuery)
        {
            spotService.AccessToken = (string)cache["access_token"];
            var criteriaSpotify = GetCriteriaClass();
            var newRecSearch = new SpotifyRecSearch();

            newRecSearch.seed_tracks = string.Join(",", criteriaSpotify.FavouriteTracks.Select(x => x.TrackID).ToList());
            newRecSearch.seed_artists = "";
            newRecSearch.seed_genres = criteriaSpotify.seed_genres;
            newRecSearch.market = "SE";
            newRecSearch.limit = 50;

            newRecSearch.target_popularity = criteriaSpotify.target_popularity;
            newRecSearch.target_danceability = criteriaSpotify.target_danceability;
            newRecSearch.target_energy = criteriaSpotify.target_energy;
            newRecSearch.target_tempo = criteriaSpotify.target_tempo;
            newRecSearch.target_valence = criteriaSpotify.target_valence;

            var recResults = spotService.GetRecommendations(newRecSearch);

            ViewBag.Recommendations = recResults;

            ViewBag.GenreList = spotService.genres;

            return View("Recommendations", criteriaSpotify);
        }

    }
}

RecommendMusicToMe/Views/Spotify/ListSearchResults.cshtml
@model RecommendMusicToMe.Models.SearchCriteriaModel
@{
    ViewBag.Title = "Spotify Search Results";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListSearchResults</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @*<input type="hidden" value="" name="addtrackid" />
            <input type="hidden" value="" name="addtrackname" />*@

        <div class="row">
            <div class="col-md-6">
                <p>Enter your search text below</p>
            </div>
            <div class="col-md-6">
                <p>Hit this button to search</p>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <p>
                    @Html.LabelFor(m => m.SearchText, new { style = "display:inline;" }) -
                    @Html.TextBoxFor(model => model.SearchText, htmlAttributes: new { @class = "form-control", style = "display:inline;" })

                <p>
                    @Html.CheckBoxFor(model => model.ListAlbums)
                    @Html.LabelFor(m => m.ListAlbums)

                    @Html.CheckBoxFor(model => model.ListArtists)
                    @Html.LabelFor(m => m.ListArtists)

                    @Html.CheckBoxFor(model => model.ListPlaylist)
                    @Html.LabelFor(m => m.ListPlaylist)

                    @Html.CheckBoxFor(model => model.ListTrack)
                    @Html.LabelFor(m => m.ListTrack)
                </p>
                </p>
            </div>
            <div class="col-md-6">
                <p>
                    @*Html.ActionLink("Spotify Search", "ListSearchResults", "Spotify", null,
                        new
                        {
                            @class = "btn btn-info",
                            @id = "spotifySearch",
                            onclick = "this.href += '?searchNow=' + document.getElementById('SearchText').value + " +
                                "'&ShowAlbum=' + document.getElementById('ListAlbums').checked + " +
                                "'&ShowPlaylist=' + document.getElementById('ListPlaylist').checked + " +
                                "'&ShowTrack=' + document.getElementById('ListTrack').checked + " +
                                "'&ShowArtist=' + document.getElementById('ListArtists').checked + " +
                                "'&ShowPage=1';"
                        })*@
                </p>
                <p><input type="submit" value="Refresh Search" class="btn btn-info" /></p>
            </div>

        </div>


        <div class="row">
            <div class="col-md-6">
                <p>
                    @if (Model.PageNumber > 1)
                    {
                        @Html.ActionLink("<< Previous Page", "ListSearchResults", "Spotify", null,
                                                          new
                                                          {
                                                              @class = "btn btn-info",
                                                              @id = "spotifySearch",
                                                              onclick = "this.href += '?searchNow=' + document.getElementById('SearchText').value + " +
                                                                  "'&ShowAlbum=' + document.getElementById('checkAlbums').checked + " +
                                                                  "'&ShowPlaylist=' + document.getElementById('ListPlaylist').checked + " +
                                                                  "'&ShowTrack=' + document.getElementById('ListTrack').checked + " +
                                                                  "'&ShowArtist=' + document.getElementById('ListArtists').checked + " +
                                                                  "'&ShowPage=' + " + Model.PreviousPage() + ";"
                                                          })
                    }
                </p>
            </div>
            <div class="col-md-6">
                <p>
                    @if (Model.IsNextPage)
                    {
                        @*Html.ActionLink("Next Page >>", "ListSearchResults", "Spotify", null,
                            new
                            {
                                @class = "btn btn-info",
                                @id = "spotifySearch",
                                onclick = "this.href += '?searchNow=' + document.getElementById('SearchText').value + " +
                                    "'&ShowAlbum=' + document.getElementById('checkAlbums').checked + " +
                                    "'&ShowPlaylist=' + document.getElementById('ListPlaylist').checked + " +
                                    "'&ShowTrack=' + document.getElementById('ListTrack').checked + " +
                                    "'&ShowArtist=' + document.getElementById('ListArtists').checked + " +
                                    "'&ShowPage=' + " + Model.NextPage() + ";"
                            })*@
                    }
                </p>


            </div>


        </div>


        <div class="row">
            <div class="col-md-6">
                @if (Model.FavouriteTracks.Count() == 0)
                {
                    <p><strong>No favourite tracks chosen yet.  Please click on a Track to add it to favourites</strong></p>
                }
                else
                {
                    <p>Favourite Tracks (up to 5)</p>
                    for (int ii = 0; ii < Model.FavouriteTracks.Count(); ii++)
                    {
                        <p>
                            @*Html.EditorFor(m => m.FavouriteTracks[ii], "FavouriteTrackItem")*@
                            @Html.HiddenFor(m => m.FavouriteTracks[ii].TrackID)
                            @Html.EditorFor(m => m.FavouriteTracks[ii].TrackName)
                        </p>
                    }
                }
            </div>
            <div class="col-md-6">
                <p>Click this button to view the recommendations by Spotify, using more criteria you can choose from. <br/>You may use the back button to modify this page again</p>
                @if (Model.FavouriteTracks.Count() > 0)
                {
                    @Html.ActionLink("Get Recommendations", "GetRecommendations", "Spotify", null, new { @class = "btn btn-info" })
                }


            </div>
        </div>
    }
    <h2>Spotify search results</h2>
    <div>

        <div class="row">
            @if (Model.ListPlaylist)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    <p><strong>Playlists</strong></p>
                </div>
            }
            @if (Model.ListAlbums)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    <p><strong>Albums</strong></p>
                </div>
            }
            @if (Model.ListArtists)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    <p><strong>Artists</strong></p>
                </div>
            }
            @if (Model.ListTrack)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    <p><strong>Tracks</strong></p>
                </div>
            }
        </div>


        <div class="row">
            @if (Model.ListPlaylist)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    @if (ViewBag.SearchSpotify != null)
                    {
                        foreach (Item4 plist in ((SpotifySearchResults)ViewBag.SearchSpotify).playlists.items)
                        {
                            <a href=@plist.external_urls.spotify>@plist.name</a><br />
                        }
                    }
                </div>
            }
            @if (Model.ListAlbums)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    @if (ViewBag.SearchSpotify != null && ((SpotifySearchResults)ViewBag.SearchSpotify).albums != null)
                    {
                        foreach (Item plist in ((SpotifySearchResults)ViewBag.SearchSpotify).albums.items)
                        {
                            <a href=@plist.external_urls.spotify>@plist.name</a><br />
                        }
                    }
                </div>
            }
            @if (Model.ListArtists)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    @if (ViewBag.SearchSpotify != null && ((SpotifySearchResults)ViewBag.SearchSpotify).artists != null)
                    {
                        foreach (Item2 plist in ((SpotifySearchResults)ViewBag.SearchSpotify).artists.items)
                        {
                            <a href=@plist.external_urls.spotify>@plist.name</a><br />
                        }
                    }
                </div>
            }
            @if (Model.ListTrack)
            {
                <div class=@Model.GetBootStrapColWidth()>
                    @if (ViewBag.SearchSpotify != null && ((SpotifySearchResults)ViewBag.SearchSpotify).tracks != null)
                    {
                        foreach (TrackObject track in ((SpotifySearchResults)ViewBag.SearchSpotify).tracks.items)
                        {
                            using (Html.BeginForm("AddFavouriteTrack", "Spotify", FormMethod.Post))
                            {
                                @Html.HiddenFor(m => m.SearchText)
                                @Html.HiddenFor(m => m.ListAlbums)
                                @Html.HiddenFor(m => m.ListArtists)
                                @Html.HiddenFor(m => m.ListPlaylist)
                                @Html.HiddenFor(m => m.ListTrack)
                                for (int ii = 0; ii < Model.FavouriteTracks.Count(); ii++)
                                {
                                    @Html.HiddenFor(m => m.FavouriteTracks[ii].TrackID)
                                    @Html.HiddenFor(m => m.FavouriteTracks[ii].TrackName)
                                }
                                <input type="hidden" value="@track.id" name="addtrackid" />
                                <input type="hidden" value="@track.name" name="addtrackname" />
                                <input type="submit" value="@track.name (@track.artists.FirstOrDefault().name)" class="btn btn-link" />
                            }
                        }
                    }
                </div>
            }
        </div>


    </div>

</body>
</html>

RecommendMusicToMe/Views/Spotify/Recommendations.cshtml
@using RecommendMusicToMe.Recommendations;
@model RecommendMusicToMe.Models.SearchCriteriaModel
@{
    ViewBag.Title = "Spotify Song Recommendations";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Songs recommended by Spotify</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Recommendations", "Spotify"))
        {
            <div class="row">
                <div class="col-md-6">
                    <strong>Your Seed values (Tracks you have chosen)</strong><br/>
                    <p>Do not edit these tracks, rather use the Back button to modify them</p>
                    @Html.HiddenFor(m => m.SearchText)
                    @Html.HiddenFor(m => m.ListAlbums)
                    @Html.HiddenFor(m => m.ListArtists)
                    @Html.HiddenFor(m => m.ListPlaylist)
                    @Html.HiddenFor(m => m.ListTrack)

                    @for (int ii = 0; ii < @Model.FavouriteTracks.Count(); ii++)
                    {
                        <p>
                            @Html.HiddenFor(m => m.FavouriteTracks[ii].TrackID)
                            Track @(ii + 1) - <strong> @Html.TextBoxFor(m => m.FavouriteTracks[ii].TrackName)</strong>
                        </p>
                    }

                </div>
                <div class="col-md-6">
                    <input type="submit" value="Search again..." class="btn btn-info" />
                </div>

            </div>
            <div class="row">
                <p>Modify these settings to fine tune your recommendations</p>
                <div class="col-md-6">
                    <p>
                        @Html.EditorFor(m => m.target_popularity)
                        @Html.LabelFor(m => m.target_popularity)
                    </p>
                    <p>
                        @Html.EditorFor(m => m.target_danceability)
                        @Html.LabelFor(m => m.target_danceability)
                    </p>
                    <p>
                        @Html.EditorFor(m => m.target_energy)
                        @Html.LabelFor(m => m.target_energy)
                    </p>
                    <p>
                        @Html.EditorFor(m => m.target_tempo)
                        @Html.LabelFor(m => m.target_tempo)
                    </p>
                    <p>
                        @Html.EditorFor(m => m.target_valence)
                        @Html.LabelFor(m => m.target_valence)
                    </p>
                    <p>
                        @Html.EditorFor(m => m.seed_genres)
                        @Html.LabelFor(m => m.seed_genres)
                    </p>
                </div>
            </div>
        }
    </div>
    <div>
        <div class="row">
            <div class="col-md-6">
                <p><strong>Recommended tracks for you</strong></p>
                @if (ViewBag.Recommendations != null && ((SpotifyRecommendations)ViewBag.Recommendations).tracks != null)
                {
                    foreach (Track track in ((SpotifyRecommendations)ViewBag.Recommendations).tracks)
                    {
                        <a href=@track.external_urls.spotify>(@track.artists.First().name) @track.name</a><br />
                    }
                }
                @*ViewBag.GenreList*@

            </div>
            <div class="col-md-6">
                <p><strong>Genres to choose from, type these in manually</strong></p>
                @if (ViewBag.GenreList != null && ((List<string>)ViewBag.GenreList) != null)
                {
                    foreach (string genre in ((List<string>)ViewBag.GenreList))
                    {
                        @genre<br />
                    }
                }
                @*ViewBag.GenreList*@

            </div>
        </div>
    </div>
</body>
</html>

RecommendMusicToMe/Views/Spotify/callback.cshtml
@{
    ViewBag.Title = "callback";
}
<script type="text/javascript" language="javascript">
    var hashes = window.location.hash;
    hashes = hashes.replace('#', '?');
    if (hashes !== "")
        window.location = hashes;
</script>
<div class="row">
    <div class="col-md-4">
        <p>

        </p>
    </div>
    <div class="col-md-4">
        <p>
            @Html.ActionLink("Next: Spotify Search", "ListSearchResults", "Spotify", new { SearchText = "Eye of the tiger" }, new { @class = "btn btn-info", @id = "spotifySearch" })
        </p>
    </div>
</div>
<h2>Thanks for connecting with Spotify.  Your playlists are shown below for your reference</h2>
<div>
    @if (ViewBag.Playlists != null)
    {
        foreach (Playlist plist in ViewBag.Playlists.Items)
        {
            @plist.Name;<br />
        }
    }
</div>